---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: djudorange/node-gulp-mocha
    tag: "latest"

inputs:
- name: blue-green-app-deployment

run:
  path: blue-green-app-deployment/ci/tasks/run-unit-tests
